DROP TABLE IF EXISTS paciente CASCADE;

CREATE TABLE paciente (

id INT NOT NULL AUTO_INCREMENT,
nome VARCHAR(60) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
senha VARCHAR(255) NOT NULL,
cpf VARCHAR(14) NOT NULL UNIQUE,
data_nascimento DATE NOT NULL,
genero VARCHAR(9) NOT NULL,
telefone VARCHAR(14) NOT NULL,
rua VARCHAR(40) NOT NULL,
bairro VARCHAR(30) NOT NULL,
cep VARCHAR(9) NOT NULL,
cidade VARCHAR(35) NOT NULL,
estado VARCHAR(2) NOT NULL,
CONSTRAINT paciente_pk PRIMARY KEY (id)

);
